require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/slack_users', type: :request do
  # SlackUser. As you add validations to SlackUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      SlackUser.create! valid_attributes
      get slack_users_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      slack_user = SlackUser.create! valid_attributes
      get slack_user_url(slack_user)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_slack_user_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      slack_user = SlackUser.create! valid_attributes
      get edit_slack_user_url(slack_user)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new SlackUser' do
        expect do
          post slack_users_url, params: { slack_user: valid_attributes }
        end.to change(SlackUser, :count).by(1)
      end

      it 'redirects to the created slack_user' do
        post slack_users_url, params: { slack_user: valid_attributes }
        expect(response).to redirect_to(slack_user_url(SlackUser.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new SlackUser' do
        expect do
          post slack_users_url, params: { slack_user: invalid_attributes }
        end.to change(SlackUser, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post slack_users_url, params: { slack_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested slack_user' do
        slack_user = SlackUser.create! valid_attributes
        patch slack_user_url(slack_user), params: { slack_user: new_attributes }
        slack_user.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the slack_user' do
        slack_user = SlackUser.create! valid_attributes
        patch slack_user_url(slack_user), params: { slack_user: new_attributes }
        slack_user.reload
        expect(response).to redirect_to(slack_user_url(slack_user))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        slack_user = SlackUser.create! valid_attributes
        patch slack_user_url(slack_user), params: { slack_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested slack_user' do
      slack_user = SlackUser.create! valid_attributes
      expect do
        delete slack_user_url(slack_user)
      end.to change(SlackUser, :count).by(-1)
    end

    it 'redirects to the slack_users list' do
      slack_user = SlackUser.create! valid_attributes
      delete slack_user_url(slack_user)
      expect(response).to redirect_to(slack_users_url)
    end
  end
end
