require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/task_events', type: :request do
  # TaskEvent. As you add validations to TaskEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      TaskEvent.create! valid_attributes
      get task_events_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      task_event = TaskEvent.create! valid_attributes
      get task_event_url(task_event)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_task_event_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      task_event = TaskEvent.create! valid_attributes
      get edit_task_event_url(task_event)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new TaskEvent' do
        expect do
          post task_events_url, params: { task_event: valid_attributes }
        end.to change(TaskEvent, :count).by(1)
      end

      it 'redirects to the created task_event' do
        post task_events_url, params: { task_event: valid_attributes }
        expect(response).to redirect_to(task_event_url(TaskEvent.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new TaskEvent' do
        expect do
          post task_events_url, params: { task_event: invalid_attributes }
        end.to change(TaskEvent, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post task_events_url, params: { task_event: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested task_event' do
        task_event = TaskEvent.create! valid_attributes
        patch task_event_url(task_event), params: { task_event: new_attributes }
        task_event.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the task_event' do
        task_event = TaskEvent.create! valid_attributes
        patch task_event_url(task_event), params: { task_event: new_attributes }
        task_event.reload
        expect(response).to redirect_to(task_event_url(task_event))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        task_event = TaskEvent.create! valid_attributes
        patch task_event_url(task_event), params: { task_event: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested task_event' do
      task_event = TaskEvent.create! valid_attributes
      expect do
        delete task_event_url(task_event)
      end.to change(TaskEvent, :count).by(-1)
    end

    it 'redirects to the task_events list' do
      task_event = TaskEvent.create! valid_attributes
      delete task_event_url(task_event)
      expect(response).to redirect_to(task_events_url)
    end
  end
end
