require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/task_send_histories', type: :request do
  # TaskSendHistory. As you add validations to TaskSendHistory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      TaskSendHistory.create! valid_attributes
      get task_send_histories_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      task_send_history = TaskSendHistory.create! valid_attributes
      get task_send_history_url(task_send_history)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_task_send_history_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      task_send_history = TaskSendHistory.create! valid_attributes
      get edit_task_send_history_url(task_send_history)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new TaskSendHistory' do
        expect do
          post task_send_histories_url, params: { task_send_history: valid_attributes }
        end.to change(TaskSendHistory, :count).by(1)
      end

      it 'redirects to the created task_send_history' do
        post task_send_histories_url, params: { task_send_history: valid_attributes }
        expect(response).to redirect_to(task_send_history_url(TaskSendHistory.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new TaskSendHistory' do
        expect do
          post task_send_histories_url, params: { task_send_history: invalid_attributes }
        end.to change(TaskSendHistory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post task_send_histories_url, params: { task_send_history: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested task_send_history' do
        task_send_history = TaskSendHistory.create! valid_attributes
        patch task_send_history_url(task_send_history), params: { task_send_history: new_attributes }
        task_send_history.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the task_send_history' do
        task_send_history = TaskSendHistory.create! valid_attributes
        patch task_send_history_url(task_send_history), params: { task_send_history: new_attributes }
        task_send_history.reload
        expect(response).to redirect_to(task_send_history_url(task_send_history))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        task_send_history = TaskSendHistory.create! valid_attributes
        patch task_send_history_url(task_send_history), params: { task_send_history: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested task_send_history' do
      task_send_history = TaskSendHistory.create! valid_attributes
      expect do
        delete task_send_history_url(task_send_history)
      end.to change(TaskSendHistory, :count).by(-1)
    end

    it 'redirects to the task_send_histories list' do
      task_send_history = TaskSendHistory.create! valid_attributes
      delete task_send_history_url(task_send_history)
      expect(response).to redirect_to(task_send_histories_url)
    end
  end
end
